apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      role: msvc-auth
  template:
    metadata:
      labels:
        role: msvc-auth
    spec:
      containers:
        - name: msvc-auth
          image: aguzf/auth:latest
          ports:
            - containerPort: 9000
              #esta en la variable de ambiente que está en application.yml
          env:
            - name: LB_USUARIOS_URI
              valueFrom:
                configMapKeyRef:
                  name: msvc-usuarios
                  key: lb_usuarios_uri
---
apiVersion: v1
kind: Service
metadata:
  name: msvc-auth
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    role: msvc-auth